spring:
  application:
    name: clonemantle
  datasource:
    url: jdbc:postgresql://localhost:5432/clonemantle
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
  web.cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    allowed-credentials: false
    max-age: 3600

server.error:
  include-message: always
  include-binding-errors: always
  include-stacktrace: never
  include-exception: false